"""initial schema - 12 tables

Revision ID: 0a6b202e858d
Revises: 
Create Date: 2026-03-26 22:28:13.092601
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '0a6b202e858d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('classrooms',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('layout_rows', sa.Integer(), nullable=False),
    sa.Column('layout_cols', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('student', 'lecturer', 'hod', name='user_role'), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('courses',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('lecturer_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('seats',
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'label', name='uq_seat_label'),
    sa.UniqueConstraint('classroom_id', 'row', 'col', name='uq_seat_position'),
    sa.UniqueConstraint('tag_id')
    )
    op.create_table('attendance_sessions',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('lecturer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', name='session_status'), nullable=False),
    sa.Column('t_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('t_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('qr_token', sa.Text(), nullable=False),
    sa.Column('freshness_delta_sec', sa.Integer(), nullable=False),
    sa.Column('min_presence_pct', sa.Integer(), nullable=False),
    sa.Column('integrity_hash', sa.String(length=64), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_course_status', 'attendance_sessions', ['course_id', 'status'], unique=False)
    op.create_table('enrollments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_enrollment_student_course')
    )
    op.create_table('attendance_records',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('present', 'rejected', 'revoked', name='attendance_status'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('revocation_reason', sa.String(length=100), nullable=True),
    sa.Column('presence_pct', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_attendance_session_student')
    )
    op.create_index('ix_attendance_records_session_status', 'attendance_records', ['session_id', 'status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('integrity_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_session', 'audit_logs', ['session_id'], unique=False)
    op.create_table('scan_reports',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('reader_device_id', sa.String(length=100), nullable=False),
    sa.Column('tags_detected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_reports_session_time', 'scan_reports', ['session_id', 'scanned_at'], unique=False)
    op.create_table('seat_state_history',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seat_state_history_session_seat_time', 'seat_state_history', ['session_id', 'seat_id', 'detected_at'], unique=False)
    op.create_table('seat_states',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seat_id', name='uq_seat_state_session_seat')
    )
    op.create_index('ix_seat_states_session', 'seat_states', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seat_states_session', table_name='seat_states')
    op.drop_table('seat_states')
    op.drop_index('ix_seat_state_history_session_seat_time', table_name='seat_state_history')
    op.drop_table('seat_state_history')
    op.drop_index('ix_scan_reports_session_time', table_name='scan_reports')
    op.drop_table('scan_reports')
    op.drop_index('ix_audit_logs_session', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_attendance_records_session_status', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_table('enrollments')
    op.drop_index('ix_session_course_status', table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_table('seats')
    op.drop_table('courses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('classrooms')
    op.drop_table('departments')
    # ### end Alembic commands ###
