"""add_seat_spatial_coords

Revision ID: c71886ab6a18
Revises: ff9c5ec99136
Create Date: 2026-04-23 01:53:44.212621
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'c71886ab6a18'
down_revision: Union[str, None] = 'ff9c5ec99136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('x_pct', sa.Float(), nullable=True))
    op.add_column('seats', sa.Column('y_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'y_pct')
    op.drop_column('seats', 'x_pct')
    # ### end Alembic commands ###
