"""add_course_classes_table

Revision ID: f8e818695b6b
Revises: 0a6b202e858d
Create Date: 2026-04-10 09:44:42.921498
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'f8e818695b6b'
down_revision: Union[str, None] = '0a6b202e858d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_classes',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('lecturer_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday'),
    sa.Column('start_time', sa.String(length=5), nullable=False, comment='HH:MM format, e.g. 10:00'),
    sa.Column('end_time', sa.String(length=5), nullable=False, comment='HH:MM format, e.g. 12:00'),
    sa.Column('group_name', sa.String(length=50), nullable=True, comment='Optional section/group label, e.g. Group A, Section 1'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('attendance_sessions', sa.Column('class_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'attendance_sessions', 'course_classes', ['class_id'], ['id'])
    op.add_column('enrollments', sa.Column('class_id', sa.UUID(), nullable=True))
    op.drop_constraint('uq_enrollment_student_course', 'enrollments', type_='unique')
    op.create_unique_constraint('uq_enrollment_student_course_class', 'enrollments', ['student_id', 'course_id', 'class_id'])
    op.create_foreign_key(None, 'enrollments', 'course_classes', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint('uq_enrollment_student_course_class', 'enrollments', type_='unique')
    op.create_unique_constraint('uq_enrollment_student_course', 'enrollments', ['student_id', 'course_id'])
    op.drop_column('enrollments', 'class_id')
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_column('attendance_sessions', 'class_id')
    op.drop_table('course_classes')
    # ### end Alembic commands ###
